In [3]:
import sys
print(sys.executable)

c:\Users\Aakash\AppData\Local\Programs\Python\Python310\python.exe


In [4]:
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install -e "C:/Users/Aakash/Downloads/Documents/Adelaide University/Semester 1/Programming in AI"

     ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.9 MB 1.9 MB/s eta 0:00:07
      --------------------------------------- 0.2/12.9 MB 2.5 MB/s eta 0:00:06
     - -------------------------------------- 0.4/12.9 MB 3.8 MB/s eta 0:00:04
     -- ------------------------------------- 0.7/12.9 MB 4.2 MB/s eta 0:00:03
     -- ------------------------------------- 0.9/12.9 MB 4.4 MB/s eta 0:00:03
     ---- ----------------------------------- 1.3/12.9 MB 5.3 MB/s eta 0:00:03
     ----- ---------------------------------- 1.7/12.9 MB 5.6 MB/s eta 0:00:02
     ------ --------------------------------- 2.1/12.9 MB 6.0 MB/s eta 0:00:02
     ------ --------------------------------- 2.1/12.9 MB 6.0 MB/s eta 0:00:02
     ------ --------------------------------- 2.1/12.9 MB 6.0 MB/s eta 0:00:02
     ------ --------------------------------- 2.1/12.9 MB 6.0 MB/s eta 0:00:02
     ------- -------------------------------- 2.3/12.9 MB 4

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Obtaining file:///C:/Users/Aakash/Downloads/Documents/Adelaide%20University/Semester%201/Programming%20in%20AI
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
  Building editable for numcompute (pyproject.toml): started
  Building editable for numcompute (pyproject.toml): finished with status 'done'
  Created wheel for numcompute: filename=numcompute-0.1.0-0.editable-py3-none-any.whl size=3779 sha256=f03899f9bf50fc1408e5e79f50f63fdee8889a8b4544a54e36b37d4eae91f35d
  Stored in directory: C:\Users\Aakash\AppData\Local\Temp\pip-ephem-wheel-cache-mn3


[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Imports

In [3]:
import numpy as np
import tempfile
from pathlib import Path

from numcompute.io import load_csv
from numcompute.preprocessing import StandardScaler, SimpleImputer, OneHotEncoder
from numcompute.sort_search import top_k, quickselect, binary_search
from numcompute.rank import rank, percentile
from numcompute.stats import mean, std, histogram, quantile
from numcompute.metrics import accuracy, precision, recall, f1, confusion_matrix, mse
from numcompute.optim import grad, jacobian
from numcompute.pipeline import Pipeline
from numcompute.benchmarking import (
    compare_functions,
    vectorized_sum_of_squares,
    loop_sum_of_squares,
    format_benchmark_table,
)

CSV loading with missing values

In [4]:
csv_text = "1,10,\n2,,0\n3,30,1\n4,40,0"

with tempfile.NamedTemporaryFile(mode="w+", suffix=".csv", delete=False) as f:
    f.write(csv_text)
    temp_path = f.name

X_raw = load_csv(temp_path, delimiter=",")
print("Loaded CSV:")
print(X_raw)

Loaded CSV:
[[ 1. 10. nan]
 [ 2. nan  0.]
 [ 3. 30.  1.]
 [ 4. 40.  0.]]


Preprocessing

In [5]:
X_num = X_raw[:, :2]
y = X_raw[:, 2]

imputer = SimpleImputer(strategy="mean")
X_imputed = imputer.fit_transform(X_num)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

print("Imputed data:")
print(X_imputed)
print("\nScaled data:")
print(X_scaled)

Imputed data:
[[ 1.         10.        ]
 [ 2.         26.66666667]
 [ 3.         30.        ]
 [ 4.         40.        ]]

Scaled data:
[[-1.34164079 -1.5430335 ]
 [-0.4472136   0.        ]
 [ 0.4472136   0.3086067 ]
 [ 1.34164079  1.2344268 ]]


One-hot Encoding

In [6]:
X_cat = np.array([["A"], ["B"], ["A"], ["C"]])
encoder = OneHotEncoder()
X_encoded = encoder.fit_transform(X_cat)

print("One-hot encoded:")
print(X_encoded)

One-hot encoded:
[[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]]


Sort/Search and Rank

In [8]:
values = np.array([10, 30, 20, 20, 50, 40])

print("Top-3 largest:")
print(top_k(values, k=3, largest=True, return_indices=False))

print("\nQuickselect k=2 (3rd smallest):")
print(quickselect(values, 2))

sorted_vals = np.sort(values)
print("\nSorted values:")
print(sorted_vals)

print("\nBinary search for 30:")
print(binary_search(sorted_vals, 30))

print("\nRanks (average ties):")
print(rank(values, method="average"))

print("\nPercentile 75:")
print(percentile(values, 75))

Top-3 largest:
[50 40 30]

Quickselect k=2 (3rd smallest):
20

Sorted values:
[10 20 20 30 40 50]

Binary search for 30:
(3, True)

Ranks (average ties):
[1.  4.  2.5 2.5 6.  5. ]

Percentile 75:
37.5


Statistics

In [9]:
print("Mean:", mean(values))
print("Std:", std(values))
print("Quantile 0.5:", quantile(values, 0.5))

counts, bins = histogram(values, bins=4)
print("\nHistogram counts:", counts)
print("Histogram bins:", bins)

Mean: 28.333333333333332
Std: 13.437096247164249
Quantile 0.5: 25.0

Histogram counts: [1 2 1 2]
Histogram bins: [10. 20. 30. 40. 50.]


Metrics

In [10]:
y_true = np.array([0, 1, 1, 0, 1])
y_pred = np.array([0, 1, 0, 0, 1])

print("Accuracy:", accuracy(y_true, y_pred))
print("Precision:", precision(y_true, y_pred))
print("Recall:", recall(y_true, y_pred))
print("F1:", f1(y_true, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_true, y_pred))

y_true_reg = np.array([1.0, 2.0, 3.0])
y_pred_reg = np.array([1.2, 1.9, 2.8])
print("MSE:", mse(y_true_reg, y_pred_reg))

Accuracy: 0.8
Precision: 1.0
Recall: 0.6666666666666666
F1: 0.8
Confusion matrix:
[[2 0]
 [1 2]]
MSE: 0.030000000000000023


Gradient and Jacobian

In [11]:
def f(x):
    return x[0] ** 2 + x[1] ** 2

def F(x):
    return np.array([
        x[0] + x[1],
        x[0] * x[1],
    ])

x = np.array([3.0, 4.0])

print("Gradient:", grad(f, x))
print("Jacobian:")
print(jacobian(F, x))

Gradient: [6. 8.]
Jacobian:
[[1. 1.]
 [4. 3.]]


Pipeline Demo

In [12]:
class DummyModel:
    def fit(self, X, y=None):
        self.threshold_ = np.mean(X[:, 0])
        return self

    def predict(self, X):
        return (X[:, 0] > self.threshold_).astype(int)

pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler()),
    ("model", DummyModel()),
])

pipe.fit(X_num, y=np.array([0, 0, 1, 1]))
preds = pipe.predict(X_num)

print("Pipeline predictions:")
print(preds)

Pipeline predictions:
[0 0 1 1]


Benchmark Table

In [13]:
x = np.random.rand(1_000_000)

result = compare_functions(
    vectorized_sum_of_squares,
    loop_sum_of_squares,
    x,
    repeat=5,
    warmup=1,
)

print(format_benchmark_table([result["first"], result["second"]]))
print("Speedup:", f"{result['speedup_vs_slow']:.2f}x")

name                      | mean_time    | median_time  | min_time     | max_time     | std_time    
--------------------------+--------------+--------------+--------------+--------------+-------------
vectorized_sum_of_squares | 4.437060e-03 | 3.950700e-03 | 3.140300e-03 | 6.457100e-03 | 1.210804e-03
loop_sum_of_squares       | 2.120439e-01 | 2.154664e-01 | 1.958034e-01 | 2.256438e-01 | 1.055008e-02
Speedup: 47.79x
